tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-secondary-fixed-variant": "#5a00c6",
                    "on-error": "#ffffff",
                    "surface": "#f8f9ff",
                    "tertiary": "#3e495d",
                    "outline-variant": "#c7c4d8",
                    "on-primary": "#ffffff",
                    "secondary": "#712ae2",
                    "surface-variant": "#d3e4fe",
                    "surface-container-high": "#dce9ff",
                    "on-surface": "#0b1c30",
                    "inverse-on-surface": "#eaf1ff",
                    "on-tertiary-fixed-variant": "#3c475a",
                    "tertiary-fixed-dim": "#bcc7de",
                    "on-primary-fixed-variant": "#3323cc",
                    "surface-tint": "#4d44e3",
                    "background": "#f8f9ff",
                    "primary-fixed-dim": "#c3c0ff",
                    "inverse-surface": "#213145",
                    "on-secondary-fixed": "#25005a",
                    "on-tertiary": "#ffffff",
                    "secondary-fixed-dim": "#d2bbff",
                    "secondary-fixed": "#eaddff",
                    "surface-container-highest": "#d3e4fe",
                    "primary-container": "#4f46e5",
                    "surface-container-low": "#eff4ff",
                    "outline": "#777587",
                    "primary": "#3525cd",
                    "secondary-container": "#8a4cfc",
                    "on-primary-container": "#dad7ff",
                    "surface-container-lowest": "#ffffff",
                    "surface-dim": "#cbdbf5",
                    "on-tertiary-fixed": "#111c2d",
                    "error-container": "#ffdad6",
                    "error": "#ba1a1a",
                    "surface-container": "#e5eeff",
                    "on-tertiary-container": "#d1dcf4",
                    "on-primary-fixed": "#0f0069",
                    "tertiary-fixed": "#d8e3fb",
                    "surface-bright": "#f8f9ff",
                    "inverse-primary": "#c3c0ff",
                    "tertiary-container": "#566175",
                    "primary-fixed": "#e2dfff",
                    "on-error-container": "#93000a",
                    "on-background": "#0b1c30",
                    "on-secondary-container": "#fffbff",
                    "on-secondary": "#ffffff",
                    "on-surface-variant": "#464555"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "xl": "64px",
                    "gutter": "24px",
                    "md": "24px",
                    "sm": "12px",
                    "xs": "4px",
                    "lg": "40px",
                    "margin": "32px",
                    "base": "8px"
            },
            "fontFamily": {
                    "body-sm": ["Hanken Grotesk"],
                    "display-xl": ["Hanken Grotesk"],
                    "label-md": ["Hanken Grotesk"],
                    "headline-lg": ["Hanken Grotesk"],
                    "body-md": ["Hanken Grotesk"],
                    "body-lg": ["Hanken Grotesk"],
                    "headline-md": ["Hanken Grotesk"]
            },
            "fontSize": {
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "display-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
            }
          },
        },
      }